volumes:
  postgres_data:
  media_data:
  logs_data:

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - media_data:/wd/media
      - logs_data:/wd/logs
    user: '1000'

  postgres:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    profiles:
      - full_dev
      - local_dev