[tool.black]
line-length = 120
target-version = ['py310', 'py311', 'py312']
# 'extend-exclude' excludes files or directories in addition to the defaults
extend-exclude = '''
(
  venv
  | \.venv
  | env
  | \.git
  | \.mypy_cache
  | \.pytest_cache
  | build
  | dist
  | static
  | media
  | migrations
  | logs
)
'''
[tool.pylint.main]
init-hook = "import sys; sys.path.insert(0, '.')"