from .comment.add_comment_to_post_view import add_comment_to_post
from .comment.comment_approve_view import comment_approve
from .comment.comment_remove_view import comment_remove
from .post.post_detail_view import post_detail
from .post.post_draft_list_view import post_draft_list
from .post.post_edit_view import post_edit
from .post.post_list_view import post_list
from .post.post_new_view import post_new
from .post.post_publish_view import post_publish
from .post.post_remove_view import post_remove
